include theos/makefiles/common.mk

TOOL_NAME = onecalldeletiontool
onecalldeletiontool_FILES = main.mm
onecalldeletiontool_FRAMEWORKS = UIKit CoreFoundation
onecalldeletiontool_LDFLAGS = -lsqlite3
include $(THEOS_MAKE_PATH)/tool.mk
